Preprocess remaster data
tunczyk101/Predictive-ML-in-TTRPG-game-design pull request #1
Opened 2024-04-09 19:02 UTC by tunczyk101

2024-04-24 13:58 UTC, j-adamczyk requested changes

2024-04-24 13:58 UTC, j-adamczyk commented on training/creating_dataset.py
> +"""maximum sells' level"""
I don't think this comment is necessary

2024-04-24 13:58 UTC, j-adamczyk commented on training/creating_dataset.py
> +        if i["type"] == "spell"  # and i["system"]["category"]["value"] == "spell"
Remove commented out code if it's not necessary

2024-04-24 13:58 UTC, j-adamczyk commented on training/save_monsters_to_books_files.py
> +    base_path = f"{os.getcwd()}/../pathfinder_2e_remaster_data"
`os.getcwd()` is not necessary here, just `../` should work

2024-04-24 13:58 UTC, j-adamczyk commented on training/save_monsters_to_books_files.py
> +    original_data_folder = base_path + "/packs_json"
Use f-string

2024-04-24 13:58 UTC, j-adamczyk commented on training/save_monsters_to_books_files.py
> +                if "json" in monster and monster[0] != "_":
Second part can be replaced by `and not monster.startswith("_")`

2024-04-24 13:58 UTC, j-adamczyk commented on training/save_monsters_to_books_files.py
> +                    with open(f"{original_data_folder}/{folder}/{monster}") as f:
Maybe `as monster_file`?

2024-04-24 13:58 UTC, j-adamczyk commented on training/splitting_dataset.py
> +        X_test.drop(columns=["book"], inplace=True)
Do not use `inplace` if you don't have to, replace variable instead

2024-04-24 19:28 UTC, j-adamczyk approved these changes

2024-04-24 19:28 UTC, j-adamczyk commented on training/save_monsters_to_books_files.py
> +                if "json" in monster and monster.startswith("_"):
Maybe reverse this? That way, you will have one indentation less.
```
if "json" not in monster or monster.startswith("_"):
    continue

with open(...
```

2024-04-26 14:57 UTC, tunczyk101 commented
remaster update

2024-04-26 14:58 UTC, merged