Create a baseline
tunczyk101/Predictive-ML-in-TTRPG-game-design pull request #11
Opened 2024-11-25 15:54 UTC by ossimon

2025-01-12 21:18 UTC, tunczyk101 requested changes
Trochę mnie przytłacza ta skomplikowana idea, ale starałam się sprawdzić, na tyle ile umiem. 😅 Ogólnie -> jest OK
Jakieś drobnostki w komentarzach

2025-01-12 21:18 UTC, tunczyk101 commented on training/models/baseline.py
> +    def classify_creatures_archetype(self, row, index=None, use_lvl=True):
Po co jest ten index?

2025-01-12 21:18 UTC, tunczyk101 commented on training/models/baseline.py
> +            results.append(self.filtered_knns[archetype].predict([row[BASIC_STATS]])[0])
Wiem, że to się nie wydarzy, ale czy gdzieś jest coś, co sprawia, że nigdy nie będziemy robić `predict` na tych `None`  z `fit`?

2025-02-11 17:33 UTC, j-adamczyk commented on training/models/baseline.py
> +        return self.knn.predict(X_test[BASIC_STATS])[0]
This is used in one place, just use it there

2025-02-11 17:33 UTC, j-adamczyk commented on training/models/baseline.py
> +        return row["dexterity"] >= 3 and row["speed"] >= 25
Is this used anywhere?

2025-02-11 17:33 UTC, j-adamczyk commented on training/models/baseline.py
> +        return 0
This is used in one place, just use it there

2025-02-11 17:57 UTC, j-adamczyk commented on training/models/baseline.py
> +            and stat_distribution["Extreme"].isnull().values.any()
Why? What does it mean that there is 1 null? What are shapes of those things? This whole code section is a) very complicated b) not very well explanied in the comments

2025-02-11 17:59 UTC, j-adamczyk commented on training/models/baseline.py
> +            results.append(self.filtered_knns[archetype].predict([row[BASIC_STATS]])[0])
Plus zdecydowanie trzeba rozbić tę linijkę na kilka

2025-02-11 17:59 UTC, j-adamczyk commented on training/models/baseline.py
> +            assumed_lvl = row["level"]
When is it known? During training?

2025-03-04 18:10 UTC, ossimon commented on training/models/baseline.py
> +            "D:\\Predictive-ML-in-TTRPG-game-design\\dataset\\attribute_distributions\\modifiers.csv"
Będzie, my bad

2025-03-04 18:10 UTC, ossimon commented on training/models/baseline.py
> +        for i in range(len(self.hp_range_dist)):
Done

2025-03-04 18:11 UTC, ossimon commented on training/models/baseline.py
> +        max_lvl = 24
Bo patrzyłem na rozkłady statystyk, gdzie tak było, ale to błąd. Poprawiłem

2025-03-04 18:11 UTC, ossimon commented on training/models/baseline.py
> +            extreme = modifiers.iloc[level + 1]["Extreme"]
Uuu, nie pomyślałem o tym. Dzięki

2025-03-04 18:12 UTC, ossimon commented on training/models/baseline.py
> +    def classify_creatures_archetype(self, row, index=None, use_lvl=True):
Jakaś pozostałość. Usunąłem

2025-03-04 18:12 UTC, ossimon commented on training/models/baseline.py
> +    def predict(self, X_Test):
Ok

2025-03-04 18:13 UTC, ossimon commented on training/models/baseline.py
> +OCCURANCE_NUMS = {
Okazało się, że to niepotrzebna pozostałość z wcześniejszych wersji, więc usunąłem

2025-03-04 18:14 UTC, ossimon commented on training/models/baseline.py
> +    "splash-damage_weakness",
I didn't all use of these inside baseline. I just needed the list of all column names that I get from the trainer. Anyway, it's not needed anymore so I removed it.

2025-03-04 18:14 UTC, ossimon commented on training/models/baseline.py
> +    "aoo",
As above

2025-03-04 18:15 UTC, ossimon commented on training/models/baseline.py
> +    "spells_nr_lvl_9",
As above

2025-03-04 18:15 UTC, ossimon commented on training/models/baseline.py
> +        return self.knn.predict(X_test[BASIC_STATS])[0]
Done

2025-03-04 18:15 UTC, ossimon commented on training/models/baseline.py
> +        return row["dexterity"] >= 3 and row["speed"] >= 25
Nope, removed

2025-03-04 18:16 UTC, ossimon commented on training/models/baseline.py
> +        return 0
Done

2025-03-04 18:16 UTC, ossimon commented on training/models/baseline.py
> +            and stat_distribution["Extreme"].isnull().values.any()
I agree. I struggled with this part, so I left it this way, but it turns out it's not needed anymore. I also fixed the comments

2025-03-06 19:16 UTC, tunczyk101 commented on training/models/baseline.py
> +    "brute": 17,
Wsm to mnie teraz zastanawia dlaczego część stałych jest małymi literami a reszta dużymi, ale może taka konwencja 😅

2025-03-06 19:16 UTC, tunczyk101 commented on training/models/baseline.py
> +        self.knn.fit(self.bestiary[BASIC_STATS], self.bestiary["level"])
A tu nie można po prostu dać X i y?
Tak też może zostać

2025-03-14 12:07 UTC, j-adamczyk approved these changes

2025-03-15 17:16 UTC, tunczyk101 approved these changes

2025-03-23 23:50 UTC, merged