Models/coral_corn
tunczyk101/Predictive-ML-in-TTRPG-game-design pull request #12
Opened 2024-12-08 16:17 UTC by tunczyk101

2024-12-11 12:16 UTC, j-adamczyk requested changes

2024-12-11 12:16 UTC, j-adamczyk commented on dataset/creating_dataset.py
> +def get_max_spell_level(items_list: list[dict]):
`-> int`

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        return (y_pred_score > threshold).to(torch.int32)
>=

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        batch_size=128,
Add types

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +    def fit(self, X, y):
This would probably be quite easier with `skorch`

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        )
Like above, maybe 128 and 64?

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        return logits
`return self.network(x)`

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        batch_size=128,
Types

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        torch.manual_seed(RANDOM_STATE)
Seed in `.fit()`, not in constructor

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        torch.manual_seed(RANDOM_STATE)
Seed in `.fit()`, not in constructor

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +        )  # number processes/CPUs to use
One line above?

2024-12-11 12:16 UTC, j-adamczyk commented on training/models/coral_corn.py
> +                #### CORN loss
Why comment?

2025-01-12 21:59 UTC, tunczyk101 commented on training/models/coral_corn.py
> +                levels = levels_from_labelbatch(
Contact to author:
# coral_pytorch
# Author: Sebastian Raschka <sebastianraschka.com>

2025-03-08 21:07 UTC, tunczyk101 commented
Obecnie tylko Coral
Ten skorch z jakiegoś powodu jest dla mnie większą drogą przez mękę niż wszystko do tej pory.
Błagam o potwierdzenie, że jest ok lub o informacje co jest nie tak i dodam Corna

2025-03-08 23:11 UTC, j-adamczyk approved these changes

2025-03-08 23:11 UTC, j-adamczyk commented on training/models/coral_corn.py
> +NUM_CLASSES = 53
+1

2025-03-11 12:08 UTC, merged