Models/classic regression
tunczyk101/Predictive-ML-in-TTRPG-game-design pull request #4
Opened 2024-05-30 11:33 UTC by tunczyk101

* klasyczna regresja
* statsmodels (2 wersje)
* AOO
* zaokrąglenia

wyniki w udostępnionym arkuszu

2024-05-30 20:06 UTC, j-adamczyk requested changes

2024-05-30 20:06 UTC, j-adamczyk commented on training/rounging.py
> +from queue import PriorityQueue
Literówka w nazwie pliku

2024-05-30 20:06 UTC, j-adamczyk commented on training/train_and_evaluate_models.py
> +            "test": calculate_results(y_test, y_pred_test, False),
Lepiej ostatni argument przekazywać tutaj przez nazwę

2024-05-30 20:06 UTC, j-adamczyk commented on training/train_and_evaluate_models.py
> +            ),
Jak wyżej

2024-05-30 20:06 UTC, j-adamczyk commented on training/train_and_evaluate_models.py
> +            )[0]
To indeksowanie zrobiłbym osobno, albo w ogóle zwracał jeden najlepszy. Obecnie jest trochę neiczytelne

2024-05-30 20:06 UTC, j-adamczyk commented on training/train_and_evaluate_models.py
> +            }
Zdecydowanie trzeba to rozbić na osobne wyrażenia

2024-05-30 20:06 UTC, j-adamczyk commented on training/train_and_evaluate_models.py
> +            }
Jak wyżej - osobne wyrażenia. Tutaj się strasznie dużo dzieje wszędzie

2024-05-30 20:06 UTC, j-adamczyk commented on training/rounging.py
> +def round_prediction(predicted: float, threshold: float):
Add return type

2024-05-30 20:06 UTC, j-adamczyk commented on training/rounging.py
> +def round_prediction_error(predicted: float, true: float, threshold: float):
Return type

2024-05-30 20:06 UTC, j-adamczyk commented on training/rounging.py
> +):
Return type

2024-05-30 20:06 UTC, j-adamczyk commented on training/rounging.py
> +):
Return type

2024-05-30 20:06 UTC, j-adamczyk commented on training/rounging.py
> +        )
Rozbij to na osobne zmienne, 5 poziomów zagnieżdżenia to jest o 4 za dużo

2024-05-30 20:06 UTC, j-adamczyk commented on training/train_and_evaluate_models.py
> +                print(f"\t\t\t--> {measure}: {m_value}")
Zastanawiam się nad formatem tutaj. Może dałoby się te wyniki zapisywać do CSVki, np. Pandasem w trybie append? Bo ten format wygląda fajnie w konsoli, ale do kopiowania czy automatycznego parsowania to jest masakra

2024-05-30 20:06 UTC, j-adamczyk commented on requirements.txt
> +alembic==1.13.1 ; python_full_version >= "3.10.0" and python_full_version < "3.11.0"
Właściwie po co `requirements.txt`? Wystarczy samo Poetry i `poetry.lock`

2024-06-29 20:04 UTC, tunczyk101 commented
Wyniki są teraz w dwóch df  (zamiast dict)

2024-07-14 21:13 UTC, merged