Add metrics
tunczyk101/Predictive-ML-in-TTRPG-game-design pull request #9
Opened 2024-10-14 21:00 UTC by bogumilap

2024-10-17 15:47 UTC, ossimon commented on training/metrics.py
> +MAX_LEVEL = 22
Czy maksymalny poziom to nie 21?

2024-10-17 16:14 UTC, bogumilap commented on training/metrics.py
> +MAX_LEVEL = 22
Wg @tunczyk101 22

2024-10-17 16:34 UTC, tunczyk101 commented on training/metrics.py
> +MAX_LEVEL = 22
Ze względu na to, że istnieją modele, które wymagają, aby minimalna wartość była nieujemna to w `train_and_evaluate_models` na samum początku [dodajemy 1.](https://github.com/tunczyk101/Predictive-ML-in-TTRPG-game-design/blob/530b2d0b6858890ff6f6967d43230274e4137c62/training/train_and_evaluate_models.py#L195) 
Zatem:
Poziomy w plikach: od -1 do 21
Poziomy podawane do modeli (oraz metryk): od 0 do 22

2024-10-17 16:41 UTC, ossimon commented on training/metrics.py
> +    return result / (MAX_LEVEL + 1 - MIN_LEVEL)
Myślę, że można trochę poprawić tę funkcję pod względem nazw zmiennych i pozbyć się jednego fora. Przykładowo:

   ```
    lvl_counts = np.zeros(MAX_LEVEL - MIN_LEVEL + 1)
    sum_err_per_lvl = np.zeros(MAX_LEVEL - MIN_LEVEL + 1)

    for i, pred in enumerate(y_predicted):
        lvl_counts[pred - MIN_LEVEL] += 1
        sum_err_per_lvl[pred - MIN_LEVEL] += abs(y_true[i] - pred)

    return np.sum(sum_err_per_lvl / lvl_counts) / (MAX_LEVEL - MIN_LEVEL + 1)
```

2024-10-17 16:41 UTC, ossimon commented on training/metrics.py
> +    return result / (MAX_LEVEL + 1 - MIN_LEVEL)
Jak wyżej

2024-10-17 16:44 UTC, tunczyk101 commented on training/metrics.py
> +    return result / (MAX_LEVEL + 1 - MIN_LEVEL)
Dlaczego dla predict? To nie powinno być uśrednienie, ale dla każdego prawdziwego poziomu?

2024-10-17 16:46 UTC, tunczyk101 commented on training/metrics.py
> +    return result / (MAX_LEVEL + 1 - MIN_LEVEL)
Również jak wyżej

2024-10-17 16:47 UTC, ossimon commented on training/metrics.py
> +MAX_LEVEL = 22
Racja

2024-10-17 16:52 UTC, ossimon commented on training/metrics.py
> +    return result / (MAX_LEVEL + 1 - MIN_LEVEL)
Faktycznie. Też jeszcze teraz zauważyłem, że obie wersje dzielą przez zero

2024-10-17 16:52 UTC, tunczyk101 commented on training/metrics.py
> +        result += prediction_result / j_class_count
Tu jest potencjalny problem
Może nie być przedstawicieli danego poziomu i wtedy mamy dzielenie przez 0
Dla wartości prawdziwych raczej tak nie będzie, ale możliwość istnieje. Dla predicted się zdarza w przypadku części modeli (wiem z doświadczenia 😅).

2024-10-17 17:01 UTC, tunczyk101 commented on training/metrics.py
> +                prediction_result += (y_true[i] - y_predicted[i]) ** 2
@bogumilap
Wiem, że w artykule jest mse, ale my używamy rmse. Chcemy mieć mse, bo tak jest w artykule itp. itd. czy raczej rmse, żeby móc porównać w jakiś sposób wersję klasyczną i ważoną?

2024-10-17 17:02 UTC, ossimon commented on training/metrics.py
> +    return result / (MAX_LEVEL + 1 - MIN_LEVEL)
Poprawiając dzielenie przez zero i sprawdzając z artykułem wydaje mi się, że tak powinno być dobrze:
```
    lvl_counts = np.zeros(MAX_LEVEL - MIN_LEVEL + 1)
    sum_err_per_lvl = np.zeros(MAX_LEVEL - MIN_LEVEL + 1)

    for i, true_lvl in enumerate(y_true):
        lvl_counts[true_lvl - MIN_LEVEL] += 1
        sum_err_per_lvl[true_lvl - MIN_LEVEL] += abs(true_lvl - y_predicted[i])

    avg_err_per_lvl = sum_err_per_lvl[lvl_counts != 0] / lvl_counts[lvl_counts != 0]

    return np.sum(avg_err_per_lvl) / (MAX_LEVEL - MIN_LEVEL + 1)
```

2024-10-17 17:24 UTC, ossimon commented on training/metrics.py
> +    return result / len(y_true)
Proponuję założyć, że y_true i y_predicted to pd.DataFrame albo przekonwertować na np.array() i zrobić

`return np.sum(np.abs(y_true - y_predicted) <= 2) / len(y_true)`

2024-10-17 17:24 UTC, ossimon commented on training/metrics.py
> +from typing import List
W sumie czy możemy użyć pd.DataFrame dla y_true i y_predicted? Chyba tym najczęściej są?

2024-10-17 20:13 UTC, j-adamczyk requested changes

2024-10-17 20:13 UTC, j-adamczyk commented on training/metrics.py
> +    return result / len(y_true)
+1, zakładam, że to np.array

2024-10-17 20:13 UTC, j-adamczyk commented on training/metrics.py
> +        for i in range(len(y_predicted)):
Załóżmy, że to są macierze  NumPy'a. Wtedy to można zapisać wektorowo, najpierw maska `y_predicted == j` (właściwie to czemu w zewnętrznej pętli jest `j`, a nie `i`?), a potem w środku wzór na całych wektorach

2024-10-31 18:09 UTC, bogumilap commented on training/metrics.py
> +    return math.sqrt(mse_macroaveraged(y_true, y_predicted))
RMSE to pierwiastek z błędu średniokwadratowego

2024-10-31 19:43 UTC, j-adamczyk commented on training/metrics.py
> +    return math.sqrt(mse_macroaveraged(y_true, y_predicted))
Jest dobrze, to jest pierwiastek ze średniej

2024-11-02 15:46 UTC, ossimon approved these changes

2024-11-03 19:06 UTC, merged